### PR TITLE
Fix passing of execution options to git.

### PR DESCRIPTION
**Pull request by AlexTugarev**
Execution options were not propagated in some cases. This PR should fix most most parts relevant for Theia.

### CODE REVIEW

**Comment by AlexTugarev** [comment]
@kittaakos, please review.

**Comment by kittaakos** [comment]
@AlexTugarev, let me know if you need a new release right now.

**Comment by AlexTugarev** [comment]
@kittaakos, actually I don't like you to do that in your free time!

**Comment by AlexTugarev** [comment]
Thanks @kittaakos!

**Pull request merged**
