### PR TITLE
Updates for node 14+ and newer dependencies

### PR DESCRIPTION
**Pull request by daniel-brenot**
This PR updates most of the project dependencies, and removes the restriction on node max version. 

This also fixes some of the tests that were broken based on the commit date sorting on macos. The tests all pass on travisCI now.

### CODE REVIEW

**Comment by luizas** [comment]
Hi @daniel-brenot Any update on that PR?

**Comment by daniel-brenot** [comment]
> Hi @daniel-brenot Any update on that PR?

Still waiting on this to be merged in.

**Comment by anavarre** [comment]
Am I correct to assume that it's the one missing dependency to really make Theia compatible with Node.js 14 @kittaakos ? The 12.x EOL is coming soon https://nodejs.org/en/about/releases/ and we should likely get ready to upgrade to 14.x as soon as possible.

**Comment by kittaakos** [comment]
Thanks for the ping, @anavarre. I would love to help, but I am not a member anymore; hence I do not have write access. If this PR does not get enough attention, please ask [here](https://github.com/eclipse-theia/theia/discussions) or [here](https://community.theia-ide.org/). Good luck 🤞

**Review by msujew — APPROVED** [review]
One of the tests does not work for me on Ubuntu, but I'll fix that later, thanks for the PR!

**Pull request merged**
